# build environment
FROM node:13-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV HTTP_PROXY="http://53.93.3.100:3128"
ENV HTTPS_PROXY="https://53.93.3.100:3128"
RUN npm config set proxy http://53.93.3.100:3128
RUN npm config set proxy https://53.93.3.100:3128
COPY package.json /app/package.json
RUN npm install
RUN npm install -g react-scripts@3.0.1
COPY . /app
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
